language: d
sudo: false

d:
    - dmd-2.073.2
    - dmd-2.074.0

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libevent-dev libssl-dev

script:
    - for module in examples/*; do echo $module; dub build --single $module; done
